### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by maximpetrov** [denis-shvetcov/AVL_Tree#1]
1. Вложенные классы следует делать статическими, если из их методов не нужен доступ к объекту внешнего класса. То есть `Node` стоит сделать статическим, а вот `SubSet` можно оставить нестатическим, но тогда ему не нужна явная ссылка на внешний класс (`tree`).
1. Хорошо бы не проверять отдельно наличие элемента перед удалением/добавлением.
1. `remove` в итераторе у Вас работает не совсем правильно. Он вызывает обычное удаление, которое, во-первых, ищет этот элемент заново, а во-вторых, что куда более важно, перестраивает дерево и, в некоторых случаях, ломает Ваш итератор.
1. В `floor` и `ceiling` вполне можно отдельно рассмотреть ситуацию нахождения указанного элемента с немедленным возвращением результата.
1. `first` и `last` должны кидать `NoSuchElementException` на пустом множестве или подмножестве.
1. В `retainAll` Вы, во-первых, вызываете `contains` на переданной коллекции, сложность поиска в которой неизвестна и потенциально выше, чем в Вашем дереве. Во-вторых, тут Вы тоже удаляете элементы из дерева с помощью `remove` во время итерации по этому же дереву, что опять же иногда ломает итератор. В-третьих, возвращаемое значение Вы вычисляете неправильно: размер до удаления элементов никогда не будет больше размера после.
1. Хранить размер поддерева и вычислять его при создании не имеет смысла, ведь всё равно Вы пересчитываете его каждый раз.
1. В методах `lower`, `higher`, `floor` и `ceiling` подмножества Вы довольно странно работаете в ситуации, когда аргумент не попадает в границы подмножества. Спецификация допускает такие вызовы, так что ответ должен быть в справедлив в рамках подмножества. То есть, например, на `headSet(5, true)` вызов `lower(10)` должен вернуть наибольший элемент из подмножества, а у Вас он вернёт `null`, если в исходном множестве есть элементы между 5 и 10.
1. `add` за пределами подмножества должен кидать `IllegalArgumentException`.
1. Вызовы `headSet`, `tailSet`, `subSet` и `descendingSet` на подмножестве должны работать относительно этого подмножества, а не исходного множества. То есть ссылаться они должны на исходное множество, но границы и направление должны вычисляться исходя из границ и направления подмножества. Направление Вы учитываете, а границы нет. Например, `s.headSet(10).tailSet(5)` должно давать тот же результат, что и `s.subSet(5, 10)`. При попытке выставить границы шире, чем есть должно выбрасываться `IllegalArgumentException`. В `subSet`, кстати, Вы почему-то не учитываете текущее направление, хотя для `descendingSet` `from` и `to` будут наоборот. И да, если `from` больше `to` (или меньше для `descendingSet`) должно тоже выбрасываться `IllegalArgumentException`.
1. `removeAll` и `retainAll` на подмножестве не должны "отменяться", если какие-то из переданных элементов не попадают в границы, они должны отработать на тех элементах, которые в границы попадают.
1. `clear` на подмножестве очищать только поддерево, то есть удалять из исходного дерева только элементы, которые попадают в границы подмножества.

**Comment by denis-shvetcov** [comment]
Мне не удалось убрать проверку наличия перед добавлением и удалением.

**Comment by maximpetrov** [comment]
1. 3 и 4 не исправлены.
1. `pollFirst()` и `pollLast()` на пустом множестве должны не кидать исключение, а просто возвращать `null`.
1. Теперь Вы в `retainAll` ищете в `ArrayList`, поиск в котором не потенциально, а гарантированно медленнее.
1. Уберите вызовы `countSize()`, которые теперь ничего не делают.
1. Сейчас у `lower` и `higher` у подмножества потенциальная вычислительная сложность - O(NlogN) вместо O(logN), если Вам придётся перебрать почти все элементы исходного множества. А если в ни один элемент не попадает под условие, то Вы ещё и `NullPointerException` получите. А `floor` и `ceiling` Вы даже не попытались исправить.
1. В `isInRange` во-первых, можно не заводить переменные `fromPassed` и `toPassed`, а просто возвращать `false` при обнаружении ошибки и `true` в конце. Во-вторых, Вы неправильно оцениваете ситуацию с совпадением границ. Да, нельзя расширить множество, сделав из строгой границы нестрогую, но наоборот сузить можно.
1. Похоже, Вы где-то запутались с тем, какую границу где храните в `descendingSet`, потому что на `descendingSet` не работают `headSet` и `tailSet`.
1. Варианты `headSet` и `tailSet`, которые из `SortedSet`, у Вас работают как раньше, почти без учёта предыдущих границ. Вообще, зачем Вы копировали код в эти варианты `headSet`, `tailSet` и `subSet`, ведь проще и правильнее в них просто вызвать соответствующие варианты  с нужным указанием включения границ?
1. `addAll`, как и `add`, должно кидать исключение при попытке добавить за границы подмножества, а не возвращать `false` (Проще всего и правильнее просто в цикле вызвать `add`).
1. `removeAll` сейчас работает правильно, но лучше и проще было бы тоже просто в цикле вызвать `remove`, чтобы не заводить промежуточный список.
1. `retainAll` всё ещё работает неправильно. Если какие-то элементы не входят в подмножество, то он всё ещё ничего не делает. Если же все элементы входят в подмножество, то `retainAll` выполняется над всем множеством, а должен только над подмножеством, то есть должны удалиться только те элементы исходного множества, которые входят в подмножество, но не входят в переданную коллекцию.
1. В `clear` на подмножестве Вы сейчас передаёте в `removeAll` само подмножество, а там проходите по нему итератором и удаляете элементы из исходного множества. Это может привести к тому, что итератор сломается, ведь удаляя из множества Вы удаляете и из подмножества.
1. `remove` на итераторе подмножества у Вас не работает. Вы явно хотели запомнить все удаляемые элементы, а после итерации разом удалить, то так делать нельзя по двум причинам. Во-первых, ожидается, что удаление произойдёт немедленно, а не когда-то там потом. Во-вторых, когда потом? Вероятно, Вы потому и не доделали, что не придумали, как определить окончание итерирования. Единственное, что можно было бы считать концом, это получение в `next()` последнего элемента. Но никто не обязывает итерироваться до последнего элемента. Да и на `remove` можно для него всё ещё можно вызвать.

**Comment by denis-shvetcov** [comment]
1. Сделал удаление в обоих `retainAll` через итератор.
2.  В методах дерева `ceiling` и `floor` теперь есть проверка на наличие элемента, чтобы не пришлось проходиться по дереву в поисках его.
3. В методах `privFloor`, `privCeiling`, `privLower` и `privHigher` исправлена ситуация, когда возвращается "граница" подмножества, несмотря на то, что такого элемента может не быть. Теперь в этих местах возвращается результаты методов класса `AVLTree`.

**Comment by maximpetrov** [comment]
Забыли убрать `contains` из `ceiling`, а так всё хорошо.
